### ISSUE TITLE
path.js:8: TypeError: Path must be a string. Received true

### ISSUE THREAD

**Issue by kenorb** [gruntjs/grunt-docs#140]
I've the following error when running `grunt --tasks`:

	C:\Users\925309\Sites\foo>grunt --tasks
	path.js:8
	    throw new TypeError('Path must be a string. Received ' +
	    ^

	TypeError: Path must be a string. Received true
	    at assertPath (path.js:8:11)
	    at Object.win32.join (path.js:221:5)
	    at Object.file.exists (C:\Users\925309\Sites\foo\node_modules\grunt\lib\grunt\file.js:381:28)
	    at task.loadTasks (C:\Users\925309\Sites\foo\node_modules\grunt\lib\grunt\task.js:371:18)
	    at Array.forEach (native)
	    at Task.task.init (C:\Users\925309\Sites\foo\node_modules\grunt\lib\grunt\task.js:457:33)
	    at Object.grunt.tasks (C:\Users\925309\Sites\foo\node_modules\grunt\lib\grunt.js:120:8)
	    at Object.module.exports [as cli] (C:\Users\925309\Sites\local-development-env\node_modules\grunt\lib\grunt\cli.js:38:9)
	    at Object.<anonymous> (C:\Users\925309\AppData\Roaming\npm\node_modules\grunt-cli\bin\grunt:45:20) at Module._compile (module.js:435:26)	    at Module._compile (module.js:435:26)

My environment:
- Windows 7
- grunt-cli v0.1.13
- grunt v0.4.5

**Comment by awbacker** [comment]
FWIW I get it to now, on an old project, but on OSX.  Removing everything from the gruntfile doesn't help.  Who knows...

**Comment by hn2015likun** [comment]
I get the same problem ...

**Comment by vladikoff** [comment]
See https://github.com/gruntjs/grunt/issues/811

**Comment by wlund-pivotal** [comment]
I got the same problem and the tip to see the gruntjs/grunt#811 doesn't help me as I'm too new to node.js.  I do I know which grunt tasks to run?

**Comment by vladikoff** [comment]
@wlund-pivotal available tasks would be listed when you run `grunt --help` in your project.
